---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/tests"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    assignees:
      - luizribeiro
  - package-ecosystem: nuget
    directory: "/gemswap"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    assignees:
      - luizribeiro
