---
name: CI

# yamllint disable-line rule:truthy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.2.103"

      - run: dotnet build gemswap
      - run: dotnet test tests
      - run: >-
          dotnet test tests/gemswap.tests.csproj
          /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - uses: codecov/codecov-action@v1
